apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-server
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-server
  template:
    metadata:
      labels:
        app: fhir-server
    spec:
      containers:
      - name: fhir-server
        image: olikong/fhir-server:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fhir-server
  namespace: apps
spec:
  selector:
    app: fhir-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP