# Namespace for deployment (used by some charts; you'll also specify this when installing via Helm)
namespace: apps

replicaCount: 1

image:
  repository: olikong/fhir-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

# Optionally configure resource requests and limits
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Ingress configuration (disabled by default)
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: fhir.example.com
      paths:
        - /
  tls: []

# Node scheduling preferences (if needed)
nodeSelector: {}
tolerations: []
affinity: {}